name: "units-test"

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # Generate QR Code
  generate-qr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate QR Code
      uses: snow-actions/qrcode@v1.0.0
      with:
        text: 'https://github.com/pk1wastaken/ayya'
        path: 'qrcode.png'
    - name: Commit QR Code
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add qrcode.png
        git commit -m "Generated QR Code"
        git push origin main
    - name: Upload QR Code as artifact
      uses: actions/upload-artifact@v2
      with:
        name: qrcode
        path: qrcode.png
