name: QRCode

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate QR Code
        uses: pk1wastaken/ayya@v1.0.0
        with:
          text: 'https://github.com/pk1wastaken/ayya'
          path: 'qrcode.png'

      - name: Commit QR Code
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add qrcode.png
          git commit -m "Generated QR Code"
          git push origin main

      - name: Upload QR Code as artifact
        uses: actions/upload-artifact@v2
        with:
          name: qrcode
          path: qrcode.png
